### ISSUE TITLE
Unable to download new version

### ISSUE THREAD

**Issue by evenlk** [TerminatorIsGod/CSGORoll-Daily-Rewards-Bot#4]
I am not able to download the new version as it is detected as a virus by the browser (Google Chrome, Edge).

Edit; It is Windows Defender that is detecting it as a trojan.

**Comment by TerminatorIsGod** [comment]
Windows Defender is detecting it as a trojan since it uses the task scheduler to automatically run the program. Im not sure why its triggering it now but not before. You can tell it to ignore it following these steps:

https://www.minitool.com/news/failed-virus-detected.html

If this resource isn't good enough you can just search in google "chrome detecting virus"

**Comment by TerminatorIsGod** [comment]
I just reuploaded the latest releases and it seems to not be triggering windows defender anymore.
